services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiary-backend-docker
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env.docker
    volumes:
      - /home/ubuntu/Aiary/models:/home/ubuntu/Aiary/models:ro
      - /home/ubuntu/Aiary/media:/home/ubuntu/Aiary/media
      - /home/ubuntu/aiary-assets:/home/ubuntu/aiary-assets
